_target_: src.models.shapenet_module.SNModule

net:
  _target_: src.models.components.IDFANet.SimpleNet
  num_points: 2048

loss:
  _target_: src.loss.sn_loss.Loss
  sqrt: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [ 0.9, 0.999 ]
  eps: 1e-08
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 2
  gamma: 0.99
  last_epoch: -1

